# docker-compose up --force-recreate --build
version: "3.7"

services:

  tailor:
    build: .
    #restart: always
    ports:
      - 8080:80
    environment:
      - CONSUL_HOST=consul
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-vue-client:
    build: packages/fragment-vue-client
    environment:
      - CONSUL_HOST=consul
    depends_on:
      - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-vue-file-read:
    build: packages/fragment-vue-file-read
    environment:
      - CONSUL_HOST=consul
    depends_on:
      - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-vue-http:
    build: packages/fragment-vue-http
    environment:
      - CONSUL_HOST=consul
    depends_on:
      - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-react:
    build: packages/fragment-react
    environment:
      - CONSUL_HOST=consul
    depends_on:
      - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-dotnet:
    build: packages/fragment-dotnet
    environment:
      - CONSUL_HOST=consul
    ports:
      - 1231:1231
    depends_on:
      - consul
    # restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-common:
    build: packages/fragment-common
    environment:
      - CONSUL_HOST=consul
    ports:
      - 1234:80
    depends_on:
      - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  consul:
    image: consul
    # UI dać
