# docker-compose up --force-recreate --build
# https://medium.com/travis-on-docker/how-to-run-dockerized-apps-on-heroku-and-its-pretty-great-76e07e610e22
version: "3.7"

services:

  webapp:
    build: .
    hostname: webapp
    ports:
      - 8080:80
    environment:
      - CONSUL_HOST=consul
      - TRACING_HOST=jager
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  service-vue-client:
    build: packages/fragment-vue-client
    hostname: service-vue-client
    environment:
      - CONSUL_HOST=consul
      - TRACING_HOST=jager
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  service-vue-file-read:
    build: packages/fragment-vue-file-read
    hostname: service-vue-file-read
    environment:
      - CONSUL_HOST=consul
      - TRACING_HOST=jager
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  service-vue-http:
    build: packages/fragment-vue-http
    hostname: service-vue-http
    environment:
      - CONSUL_HOST=consul
      - TRACING_HOST=jager
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  service-react:
    build: packages/fragment-react
    hostname: service-react
    environment:
      - CONSUL_HOST=consul
      - TRACING_HOST=jager
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  service-dotnet:
    build: packages/fragment-dotnet
    environment:
      - CONSUL_HOST=consul
      - TRACING_HOST=jager
    ports:
      - 1231:1231
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  service-common:
    build: packages/fragment-common
    hostname: service-common
    environment:
      - CONSUL_HOST=consul
      - TRACING_HOST=jager
    ports:
      - 1234:80
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  consul:
    image: consul
    # UI dać

