# docker-compose up --force-recreate --build
version: "3.7"

services:

  tailor:
    build: .
    #restart: always
    ports:
      - 8080:80

  fragment-vue-http:
    build: packages/fragment-vue-http
    #restart: always

  fragment-common:
    build: packages/fragment-common
    ports:
      - 1234:80
    #restart: always

  consul:
    image: consul
    # UI dać
