# docker-compose up --force-recreate --build
# https://medium.com/travis-on-docker/how-to-run-dockerized-apps-on-heroku-and-its-pretty-great-76e07e610e22
version: "3.7"

services:




  service-vue-file-read:
    build: packages/fragment-vue-file-read
    hostname: service-vue-file-read
    ports:
    - 8080:80
    environment:
      - CONSUL_HOST=consul
      - TRACING_HOST=jaeger
    depends_on:
      - jaeger
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: "single-node"
      network.host: "0.0.0.0"

  # running jaeger at http://localhost:16686
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
    depends_on:
    - elasticsearch
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "elasticsearch:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

