# docker-compose up --force-recreate --build
version: "3.7"

services:

  tailor:
    build: .
    #restart: always
    ports:
      - 8080:80
    depends_on:
      - jaeger
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-vue-client:
    build: packages/fragment-vue-client
    depends_on:
      - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-vue-file-read:
    build: packages/fragment-vue-file-read
    depends_on:
    - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-vue-http:
    build: packages/fragment-vue-http
    depends_on:
      - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-react:
    build: packages/fragment-react
    depends_on:
      - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-dotnet:
    build: packages/fragment-dotnet
    ports:
      - 1231:1231
    depends_on:
      - consul
    # restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  fragment-common:
    build: packages/fragment-common
    ports:
      - 1234:80
    depends_on:
      - consul
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "consul:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  consul:
    image: consul
    # UI dać

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"
      network.host: "0.0.0.0"

